"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { Sidebar } from "./Sidebar"; import { Topbar } from "./Topbar"; import { OverviewView } from "./OverviewView"; import { DirectoryView } from "./DirectoryView"; import { DetailDrawer } from "./DetailDrawer"; import { DivisionsView,DocksView,HealthView,TargetsView,TeamsView } from "./ManagementViews"; import { SetupView } from "./SetupView";
import type { Activity, DashboardData, Employee, EmployeeDetailData, PeriodKey, ViewKey } from "@/types/dashboard";

let activeDetailRequest:AbortController|null=null;

export function DashboardApp({initialData}:{initialData:DashboardData}) {
  const [data,setData]=useState(initialData); const [view,setView]=useState<ViewKey>("overview"); const [period,setPeriod]=useState<PeriodKey>(initialData.period); const [mobileNav,setMobileNav]=useState(false); const [employee,setEmployee]=useState<Employee|null>(null); const [employeeDetail,setEmployeeDetail]=useState<EmployeeDetailData|null>(null); const [detailLoading,setDetailLoading]=useState(false); const [activity,setActivity]=useState<Activity|null>(null); const [search,setSearch]=useState(""); const [recordResults,setRecordResults]=useState<Activity[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [directoryScope,setDirectoryScope]=useState<{division?:string;team?:string}>({}); const requestRef=useRef<AbortController|null>(null); const searchRequestRef=useRef<AbortController|null>(null); const searchInputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();searchInputRef.current?.focus();}};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey);},[]);
  useEffect(()=>{const term=search.trim();searchRequestRef.current?.abort();if(term.length<2)return;const controller=new AbortController();searchRequestRef.current=controller;const timer=window.setTimeout(async()=>{try{const query=new URLSearchParams({q:term,period:data.period});if(data.period==="Custom Range"){query.set("start",data.range.startDate);query.set("end",data.range.endDate);}const response=await fetch(`/api/dashboard-search?${query}`,{signal:controller.signal});const body=await response.json();if(response.ok&&searchRequestRef.current===controller)setRecordResults(body);}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))setRecordResults([]);}},250);return()=>{window.clearTimeout(timer);controller.abort();};},[search,data.period,data.range.startDate,data.range.endDate]);
  const changeView=(next:ViewKey)=>{setView(next);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"auto"}));};
  async function updatePeriod(value:PeriodKey,start?:string,end?:string){setPeriod(value);localStorage.setItem("broadigo-period",value);if(value==="Custom Range"&&(!start||!end))return;requestRef.current?.abort();activeDetailRequest?.abort();setEmployee(null);setEmployeeDetail(null);const controller=new AbortController();requestRef.current=controller;setLoading(true);setError("");try{const query=new URLSearchParams({period:value});if(start)query.set("start",start);if(end)query.set("end",end);const response=await fetch(`/api/dashboard?${query}`,{signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error);if(requestRef.current===controller)setData(body);}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"Unable to refresh metrics.");}finally{if(requestRef.current===controller)setLoading(false);}}
  const results=useMemo(()=>{const term=search.trim().toLowerCase();if(!term)return[];return [...data.employees.filter(item=>[item.name,item.title,...item.teams,...(item.aliases??[])].some(v=>v.toLowerCase().includes(term))).map(item=>({kind:"Employee" as const,id:item.id,title:item.name,subtitle:`${item.title} · ${item.teams.join(", ")}`,employee:item})),...(term.length>=2?recordResults:[]).map(item=>({kind:item.type,id:item.id,title:item.summary,subtitle:`${item.employee} · #${item.channel}`,activity:item}))].slice(0,12)},[search,data.employees,recordResults]);
  function closeDrawer(){activeDetailRequest?.abort();setEmployee(null);setEmployeeDetail(null);setActivity(null)}
  async function openEmployee(item:Employee){setError("");setActivity(null);setEmployee(item);setEmployeeDetail(null);activeDetailRequest?.abort();const controller=new AbortController();activeDetailRequest=controller;setDetailLoading(true);try{const query=new URLSearchParams({employeeId:item.id,period:data.period});if(data.period==="Custom Range"){query.set("start",data.range.startDate);query.set("end",data.range.endDate);}const response=await fetch(`/api/employee-detail?${query}`,{signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error);if(activeDetailRequest===controller)setEmployeeDetail(body);}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"Unable to load employee evidence.");}finally{if(activeDetailRequest===controller)setDetailLoading(false);}}
  function openActivity(item:Activity){activeDetailRequest?.abort();setEmployee(null);setEmployeeDetail(null);setActivity(item)}
  const chooseDivision=(division:string)=>{setDirectoryScope({division});changeView("teams")}; const chooseTeam=(team:string,division:string)=>{setDirectoryScope({division,team});changeView("employees")};
  return <div className="app-shell"><Sidebar view={view} setView={changeView} open={mobileNav} close={()=>setMobileNav(false)} mode={data.mode} employeeCount={data.employees.filter(item=>item.active).length}/><main className="main-area"><Topbar period={period} setPeriod={updatePeriod} openMenu={()=>setMobileNav(true)} search={search} setSearch={setSearch} loading={loading} searchInputRef={searchInputRef}/><div className="content-wrap">{error&&<div className="error-banner">{error}</div>}
    {view==="overview"&&<OverviewView data={data} openEmployee={openEmployee} openActivity={openActivity} setView={changeView} openDivision={chooseDivision}/>} {view==="divisions"&&<DivisionsView data={data} openDivision={chooseDivision}/>} {view==="teams"&&<TeamsView data={data} division={directoryScope.division} openTeam={chooseTeam}/>} {view==="employees"&&<DirectoryView key={`${directoryScope.division??"all"}:${directoryScope.team??"all"}`} employees={data.employees} openEmployee={openEmployee} initialFilters={directoryScope}/>} {view==="docks"&&<DocksView data={data} openActivity={openActivity}/>} {view==="targets"&&<TargetsView data={data} onChanged={async()=>{const custom=data.period==="Custom Range";await updatePeriod(data.period,custom?data.range.startDate:undefined,custom?data.range.endDate:undefined)}}/>} {view==="health"&&<HealthView data={data} configure={()=>changeView("setup")}/>} {view==="setup"&&<SetupView onChanged={async()=>{const custom=data.period==="Custom Range";await updatePeriod(data.period,custom?data.range.startDate:undefined,custom?data.range.endDate:undefined)}}/>}
    <footer><span>LeadsEdge Executive Command Center</span><small>Employee performance intelligence · Asia/Karachi</small></footer></div></main>
    {search&&<div className="search-overlay" onClick={()=>setSearch("")}><div className="search-results" onClick={e=>e.stopPropagation()}><div><Search size={17}/><strong>Search results</strong><button onClick={()=>setSearch("")} aria-label="Close search"><X size={17}/></button></div>{results.length?results.map(result=><button key={`${result.kind}-${result.id}`} onClick={()=>{if("employee" in result)openEmployee(result.employee);if("activity" in result)openActivity(result.activity);setSearch("")}}><span>{result.kind}</span><div><strong>{result.title}</strong><small>{result.subtitle}</small></div></button>):<p>No employees or Slack records match “{search}”.</p>}</div></div>}<DetailDrawer employee={employee} activity={activity} detail={employeeDetail} detailLoading={detailLoading} close={closeDrawer} openActivity={openActivity}/></div>;
}
