"use client";
import { ArrowDownRight,ArrowRight,ArrowUpRight,BadgeDollarSign,CalendarCheck2,Clock3,DatabaseZap,Sparkles,Target,Users,Waypoints } from "lucide-react";
import { AnimatedSection } from "./AnimatedSection"; import { NetworkCanvas } from "./NetworkCanvas"; import { TrendChart } from "./TrendChart";
import { OPERATIONAL_SHIFT_HUMAN_LABEL, OPERATIONAL_SHIFT_LABEL } from "@/lib/time-ranges";
import type { Activity,DashboardData,Employee,ViewKey } from "@/types/dashboard";

const icons={appointments:CalendarCheck2,sales:BadgeDollarSign,revenue:BadgeDollarSign,leads:Waypoints,work:Users,docks:Target};
const accents={appointments:"brand",sales:"warm",revenue:"gold",leads:"lead",work:"neutral",docks:"danger"};
function StatusBadge({value}:{value:Employee["status"]}){return <span className={`status-badge status-${value.toLowerCase().replaceAll(" ","-")}`}>{value}</span>}
export function OverviewView({data,openEmployee,openActivity,setView,openDivision}:{data:DashboardData;openEmployee:(e:Employee)=>void;openActivity:(a:Activity)=>void;setView:(v:ViewKey)=>void;openDivision:(name:string)=>void}){
  const active=data.employees.filter(e=>e.active);const ranked=active.filter(e=>e.rankingEnabled).sort((a,b)=>(b.metricValueNumber??0)-(a.metricValueNumber??0)).slice(0,4); const last=data.health.lastEventAt?new Intl.DateTimeFormat("en-PK",{timeZone:"Asia/Karachi",dateStyle:"medium",timeStyle:"short"}).format(new Date(data.health.lastEventAt)):"No events yet";
  if(data.mode==="disconnected")return <div className="view-stack"><section className="executive-hero setup-hero"><NetworkCanvas/><div className="hero-glow"/><div className="hero-content"><div><p className="eyebrow"><DatabaseZap size={13}/> Production setup required</p><h1>Connect PostgreSQL to begin.</h1><p>This dashboard intentionally shows no sample performance data in normal execution. Configure the database, seed it, then map Slack IDs.</p><button className="primary-button" onClick={()=>setView("setup")}>Open setup <ArrowRight size={15}/></button></div></div></section></div>;
  return <div className="view-stack"><section className="executive-hero"><NetworkCanvas/><div className="hero-glow"/><div className="hero-content"><div><p className="eyebrow"><Sparkles size={13}/> Operational workdays · {data.range.label}</p><h1>Company performance.</h1><p>Metrics use persisted Slack records from the {OPERATIONAL_SHIFT_HUMAN_LABEL} Asia/Karachi shift, grouped under the date each shift started.</p></div><div className="hero-health"><span>Data mode</span><strong>{data.mode==="live"?"Live":"Demo"}</strong><small><i/> {data.mode==="live"?"PostgreSQL + Slack":"Explicit development flag"}</small></div></div><div className="hero-footer"><span><DatabaseZap size={14}/> Last event {last}</span><span><Users size={14}/> {active.length} active employees</span><span><Clock3 size={14}/> {OPERATIONAL_SHIFT_LABEL} · Asia/Karachi</span></div></section>
  <AnimatedSection className="kpi-grid">{data.metrics.map((kpi)=>{const Icon=icons[kpi.kind];const positive=(kpi.delta??0)>=0;return <article className="glass-card kpi-card" key={kpi.label}><div className={`kpi-icon ${accents[kpi.kind]}`}><Icon size={18}/></div><div className="kpi-head"><span>{kpi.label}</span>{kpi.delta!=null&&<em className={positive?"positive":"negative"}>{positive?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {Math.abs(kpi.delta)}%</em>}</div><strong>{kpi.value}</strong><small>{kpi.note}</small></article>})}</AnimatedSection>
  <AnimatedSection><div className="section-heading"><div><p className="eyebrow">Operating groups</p><h2>Division performance</h2></div><button className="text-button" onClick={()=>setView("divisions")}>View all divisions <ArrowRight size={15}/></button></div>{data.divisions.length?<div className="division-grid">{data.divisions.map(d=><button className={`glass-card division-card ${d.accent}`} key={d.name} onClick={()=>openDivision(d.name)}><div className="division-top"><span>{d.eyebrow}</span><ArrowRight size={17}/></div><h3>{d.name}</h3><div className="division-output-list">{d.outputs.length?d.outputs.map(output=><span key={output.label}><strong>{output.value}</strong><small>{output.label}</small></span>):<span><strong>0</strong><small>No recorded output</small></span>}</div></button>)}</div>:<Empty text="No division output in this period."/>}</AnimatedSection>
  <div className="overview-columns"><AnimatedSection className="glass-card attention-card"><div className="card-title"><div><p className="eyebrow">Signal, not noise</p><h2>Needs attention</h2></div></div><Empty text={data.health.unmappedEmployees?`${data.health.unmappedEmployees} Slack user IDs need employee mapping.`:"No automated attention flags for this period."}/></AnimatedSection><AnimatedSection className="glass-card leaderboard-card"><div className="card-title"><div><p className="eyebrow">Comparable roles only</p><h2>Top performers</h2></div></div>{ranked.length?<div className="leader-list">{ranked.map((e,i)=><button key={e.id} onClick={()=>openEmployee(e)}><span className="rank">0{i+1}</span><span className={`person-avatar avatar-${i}`}>{e.initials}</span><div><strong>{e.name}</strong><small>{e.title}</small></div><div className="leader-metric"><strong>{e.metricValue}</strong><StatusBadge value={e.status}/></div></button>)}</div>:<Empty text="No ranked output in this period."/>}</AnimatedSection></div>
  <AnimatedSection className="glass-card trend-card"><div className="card-title"><div><p className="eyebrow">Output over time</p><h2>Appointment trend</h2></div></div><TrendChart data={data.trend}/></AnimatedSection>
  <AnimatedSection className="glass-card activity-card"><div className="card-title"><div><p className="eyebrow">Raw evidence available</p><h2>Recent employee activity</h2></div></div>{data.activities.length?<div className="activity-table"><div className="activity-header"><span>Employee</span><span>Activity</span><span>Source</span><span>When</span><span/></div>{data.activities.map(a=><button key={a.id} onClick={()=>openActivity(a)}><span className="activity-person"><i>{a.employee.split(" ").map(w=>w[0]).slice(0,2).join("")}</i><strong>{a.employee}</strong></span><span><b className={`activity-type type-${a.type.toLowerCase().replace(" ","-")}`}>{a.type}</b><small>{a.summary}</small></span><span className="channel">#{a.channel}</span><span>{a.timestamp}</span><ArrowRight size={15}/></button>)}</div>:<Empty text="No parsed Slack activity in this period."/>}</AnimatedSection></div>;
}
function Empty({text}:{text:string}){return <div className="empty-state"><Clock3 size={22}/><strong>{text}</strong><p>Change the date range or complete Slack synchronization.</p></div>}
