"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, PlugZap, Save, Users } from "lucide-react";

type Channel = { id:string; name:string; workspaceId:string; slackChannelId:string; active:boolean };
type Person = { id:string; name:string; workspaceId:string|null; slackUserId:string|null; displayName:string|null };
export function SetupView({onChanged}:{onChanged?:()=>void|Promise<void>}) {
  const [channels,setChannels]=useState<Channel[]>([]); const [people,setPeople]=useState<Person[]>([]); const [workspace,setWorkspace]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  const load=()=>fetch("/api/setup/mappings").then(async r=>{const body=await r.json(); if(!r.ok) throw new Error(body.error); setChannels(body.channels);setPeople(body.employees);setWorkspace(body.channels.find((c:Channel)=>!c.workspaceId.startsWith("UNCONFIGURED"))?.workspaceId??body.employees.find((p:Person)=>p.workspaceId)?.workspaceId??"");}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false));
  useEffect(()=>{void load();},[]);
  async function save(body:object){setMessage("");const response=await fetch("/api/setup/mappings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){setMessage(result.error);return;}setMessage("Mapping saved. Dashboard data refreshed.");await load();await onChanged?.();}
  if(loading)return <div className="setup-loading"><LoaderCircle className="spin"/> Loading mappings…</div>;
  return <div className="view-stack"><div className="page-heading"><div><p className="eyebrow">Production connection</p><h1>Slack identity mapping</h1><p>Map the seeded reporting channels and employees to IDs from your real Slack workspace.</p></div><span className="setup-secure"><CheckCircle2 size={16}/> Secrets stay in environment variables</span></div>
    {message&&<div className="target-note"><PlugZap size={19}/><strong>{message}</strong></div>}
    <section className="glass-card data-section setup-card"><div className="card-title"><div><p className="eyebrow">Workspace</p><h2>Slack workspace ID</h2></div></div><label className="setup-field"><span>Workspace ID</span><input value={workspace} onChange={e=>setWorkspace(e.target.value)} placeholder="T0123456789"/><small>Find this in a Slack event payload as team_id.</small></label></section>
    <section className="glass-card data-section setup-card"><div className="card-title"><div><p className="eyebrow">Eight-channel whitelist</p><h2>Reporting channels</h2></div><span className="count-pill">{channels.filter(c=>c.active&&!c.slackChannelId.startsWith("UNCONFIGURED")).length} / {channels.length}</span></div><div className="mapping-list">{channels.map(channel=><div key={channel.id}><div><strong>#{channel.name}</strong><small>{channel.active?"Events enabled":"Not active"}</small></div><input value={channel.slackChannelId.startsWith("UNCONFIGURED")?"":channel.slackChannelId} onChange={e=>setChannels(list=>list.map(c=>c.id===channel.id?{...c,slackChannelId:e.target.value}:c))} placeholder="C0123456789"/><button className="secondary-button" onClick={()=>save({type:"channel",id:channel.id,workspaceId:workspace,slackChannelId:channel.slackChannelId,active:true})}><Save size={14}/> Save</button></div>)}</div></section>
    <section className="glass-card data-section setup-card"><div className="card-title"><div><p className="eyebrow">People</p><h2>Employee Slack user IDs</h2></div><Users size={18}/></div><div className="mapping-list people-mapping">{people.map(person=><div key={person.id}><div><strong>{person.name}</strong><small>{person.displayName??"Seeded employee"}</small></div><input value={person.slackUserId??""} onChange={e=>setPeople(list=>list.map(p=>p.id===person.id?{...p,slackUserId:e.target.value}:p))} placeholder="U0123456789"/><button className="secondary-button" disabled={!person.slackUserId} onClick={()=>save({type:"employee",employeeId:person.id,workspaceId:workspace,slackUserId:person.slackUserId,displayName:person.name})}><Save size={14}/> Save</button></div>)}</div></section>
  </div>;
}
